const {deviceEndpoints, numeric} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['esp32c6'],
    model: 'esp32c6',
    vendor: 'ESPRESSIF',
    description: 'Custom water tank level sensor',
    extend: [
        deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8}}), 
        numeric({
            name: 'Distance',
            endpointNames: ["1"],
            cluster: 'genAnalogValue',
            attribute: 'presentValue',
            description: 'Distance to top of water',
            unit: 'cm',
            access: 'ALL',
            precision: 2,
            reporting: null,
        }),
        numeric({
            name: 'Volume',
            endpointNames: ["2"],
            cluster: 'genAnalogValue',
            attribute: 'presentValue',
            description: 'Volume of water in tank',
            unit: 'L',
            access: 'ALL',
            precision: 0,
            reporting: null,
        }),
        numeric({
            name: 'Percentage',
            endpointNames: ["3"],
            cluster: 'genAnalogValue',
            attribute: 'presentValue',
            description: 'Percent full',
            unit: '%',
            access: 'ALL',
            precision: 0,
            reporting: null,
        }),
        numeric({
            name: 'Tank minimum distance measurement',
            endpointNames: ["4"],
            cluster: 'genAnalogValue',
            attribute: 'presentValue',
            description: 'Distance from ultrasonic sensor to top of water when tank is full.',
            unit: 'cm',
            access: 'ALL',
            precision: 0,
            reporting: null,
        }),
        numeric({
            name: 'Tank maximum distance measurement',
            endpointNames: ["5"],
            cluster: 'genAnalogValue',
            attribute: 'presentValue',
            description: 'Distance from ultrasonic sensor to top of water when tank is empty.',
            unit: 'cm',
            access: 'ALL',
            precision: 0,
            reporting: null,
        }),
        numeric({
            name: 'Tank capacity',
            endpointNames: ["6"],
            cluster: 'genAnalogValue',
            attribute: 'presentValue',
            description: 'Tank maximum capacity',
            unit: 'L',
            access: 'ALL',
            precision: 0,
            reporting: null,
        }),
        numeric({
            name: 'Distance delta',
            endpointNames: ["7"],
            cluster: 'genAnalogValue',
            attribute: 'presentValue',
            description: 'Minimum change in distance measurement for an update to be sent',
            unit: 'cm',
            access: 'ALL',
            precision: 0,
            reporting: null,
        }),
        numeric({
            name: 'Distance read period',
            endpointNames: ["8"],
            cluster: 'genAnalogValue',
            attribute: 'presentValue',
            description: 'Time between ultrasonic distance reads',
            unit: 's',
            access: 'ALL',
            precision: 0,
            reporting: null,
        }),
    ],
    meta: {"multiEndpoint":true},
};

module.exports = definition;

// Helpful references
// https://github.com/Koenkk/zigbee-herdsman-converters/blob/df5717b482f26bf106688f068f4fe76fd763dcb1/src/devices/pushok.ts#L81
// https://github.com/Koenkk/zigbee-herdsman-converters/blob/df5717b482f26bf106688f068f4fe76fd763dcb1/src/lib/modernExtend.ts#L2115